import { MediaItem } from "@/types";

export const mockMediaItems: MediaItem[] = [
  {
    id: "1",
    title: "Dune: Part Two",
    creator: "Denis Villeneuve",
    type: "movie",
    status: "COMPLETED",
    releaseYear: 2024,
    genre: ["Sci-Fi", "Adventure"],
    description:
      "Paul Atreides unites with Chani and the Fremen while seeking revenge against the conspirators who destroyed his family. Facing a choice between the love of his life and the fate of the known universe, he endeavors to prevent a terrible future only he can foresee.",
    coverUrl: "https://images.unsplash.com/photo-1446776811953-b23d57bd21aa?w=400&h=600&fit=crop",
    rating: 9.1,
    addedAt: "2024-03-01T10:00:00Z",
    completedAt: "2024-03-05T20:00:00Z",
  },
  {
    id: "2",
    title: "The Legend of Zelda: Tears of the Kingdom",
    creator: "Nintendo",
    type: "game",
    status: "USING",
    releaseYear: 2023,
    genre: ["Action-Adventure", "Open World"],
    description:
      "An epic adventure across the land and skies of Hyrule. Unexplained calamity has struck Hyrule — Link sets off on a journey to discover what lies in the murky darkness below the surface.",
    coverUrl: "https://images.unsplash.com/photo-1550745165-9bc0b252726f?w=400&h=600&fit=crop",
    rating: 9.5,
    addedAt: "2023-05-12T10:00:00Z",
  },
  {
    id: "3",
    title: "Cowboy Carter",
    creator: "Beyoncé",
    type: "music",
    status: "OWNED",
    releaseYear: 2024,
    genre: ["Country", "R&B", "Pop"],
    description:
      "The eighth studio album by Beyoncé, exploring country music and Americana through a bold artistic statement about belonging and identity in American culture.",
    coverUrl: "https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400&h=600&fit=crop",
    rating: 8.7,
    addedAt: "2024-03-29T10:00:00Z",
  },
  {
    id: "4",
    title: "Oppenheimer",
    creator: "Christopher Nolan",
    type: "movie",
    status: "COMPLETED",
    releaseYear: 2023,
    genre: ["Drama", "Biography", "History"],
    description:
      "The story of American scientist J. Robert Oppenheimer and his role in the development of the atomic bomb during World War II.",
    coverUrl: "https://images.unsplash.com/photo-1518770660439-4636190af475?w=400&h=600&fit=crop",
    rating: 8.9,
    addedAt: "2023-07-21T10:00:00Z",
    completedAt: "2023-07-22T23:00:00Z",
  },
  {
    id: "5",
    title: "Baldur's Gate 3",
    creator: "Larian Studios",
    type: "game",
    status: "WISHLIST",
    releaseYear: 2023,
    genre: ["RPG", "Fantasy"],
    description:
      "An epic RPG set in the Forgotten Realms universe. Gather your party, and return to the Forgotten Realms in a tale of fellowship and betrayal, sacrifice and survival.",
    coverUrl: "https://images.unsplash.com/photo-1511512578047-dfb367046420?w=400&h=600&fit=crop",
    rating: 9.8,
    addedAt: "2024-01-15T10:00:00Z",
  },
  {
    id: "6",
    title: "Shogun",
    creator: "FX / Hulu",
    type: "tv",
    status: "COMPLETED",
    releaseYear: 2024,
    genre: ["Drama", "Historical", "Action"],
    description:
      "Set in feudal Japan at the turn of the 17th century, an English navigator becomes embroiled in a dangerous struggle for power.",
    coverUrl: "https://images.unsplash.com/photo-1545569341-9eb8b30979d9?w=400&h=600&fit=crop",
    rating: 9.4,
    addedAt: "2024-02-27T10:00:00Z",
    completedAt: "2024-04-23T20:00:00Z",
  },
  {
    id: "7",
    title: "The Creative Act",
    creator: "Rick Rubin",
    type: "book",
    status: "OWNED",
    releaseYear: 2023,
    genre: ["Non-Fiction", "Creativity", "Philosophy"],
    description:
      "Music producer Rick Rubin shares his philosophy on creativity, offering universal insights and guidance on how to live a creative life.",
    coverUrl: "https://images.unsplash.com/photo-1481627834876-b7833e8f5570?w=400&h=600&fit=crop",
    rating: 8.2,
    addedAt: "2024-04-10T10:00:00Z",
  },
  {
    id: "8",
    title: "Interstellar",
    creator: "Christopher Nolan",
    type: "movie",
    status: "OWNED",
    releaseYear: 2014,
    genre: ["Sci-Fi", "Drama", "Adventure"],
    description:
      "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
    coverUrl: "https://images.unsplash.com/photo-1419242902214-272b3f66ee7a?w=400&h=600&fit=crop",
    rating: 8.7,
    addedAt: "2024-05-01T10:00:00Z",
  },
  {
    id: "9",
    title: "Elden Ring",
    creator: "FromSoftware",
    type: "game",
    status: "COMPLETED",
    releaseYear: 2022,
    genre: ["Action RPG", "Souls-like"],
    description:
      "An action RPG set in the Lands Between, developed in collaboration between Hidetaka Miyazaki and George R.R. Martin.",
    coverUrl: "https://images.unsplash.com/photo-1542751371-adc38448a05e?w=400&h=600&fit=crop",
    rating: 9.6,
    addedAt: "2024-02-01T10:00:00Z",
  },
  {
    id: "10",
    title: "Hit Me Hard and Soft",
    creator: "Billie Eilish",
    type: "music",
    status: "WISHLIST",
    releaseYear: 2024,
    genre: ["Pop", "Alt-Pop", "Indie"],
    description:
      "The third studio album by Billie Eilish, featuring a blend of introspective ballads and upbeat tracks.",
    coverUrl: "https://images.unsplash.com/photo-1514320291840-2e0a9bf2a9ae?w=400&h=600&fit=crop",
    rating: 8.5,
    addedAt: "2024-05-17T10:00:00Z",
  },
  {
    id: "11",
    title: "Poor Things",
    creator: "Yorgos Lanthimos",
    type: "movie",
    status: "COMPLETED",
    releaseYear: 2023,
    genre: ["Fantasy", "Comedy", "Drama"],
    description:
      "The incredible tale about the fantastical evolution of Bella Baxter, a young woman brought back to life by the brilliant and unorthodox scientist Dr. Godwin Baxter.",
    coverUrl: "https://images.unsplash.com/photo-1485846234645-a62644f84728?w=400&h=600&fit=crop",
    rating: 8.3,
    addedAt: "2024-01-25T10:00:00Z",
    completedAt: "2024-01-28T21:00:00Z",
  },
  {
    id: "12",
    title: "GNX",
    creator: "Kendrick Lamar",
    type: "music",
    status: "OWNED",
    releaseYear: 2024,
    genre: ["Hip-Hop", "Rap"],
    description:
      "A surprise album released by Kendrick Lamar, continuing his dominance in the hip-hop world with introspective and hard-hitting tracks.",
    coverUrl: "https://images.unsplash.com/photo-1470225620780-dba8ba36b745?w=400&h=600&fit=crop",
    rating: 9.0,
    addedAt: "2024-11-22T10:00:00Z",
  },
];

export const mockStats = {
  total: mockMediaItems.length,
  owned: mockMediaItems.filter((m) => m.status === "OWNED").length,
  wishlist: mockMediaItems.filter((m) => m.status === "WISHLIST").length,
  completed: mockMediaItems.filter((m) => m.status === "COMPLETED").length,
};

export const recentlyAdded = [...mockMediaItems]
  .sort((a, b) => new Date(b.addedAt).getTime() - new Date(a.addedAt).getTime())
  .slice(0, 6);
